
name: Deploy to S3

on:
  workflow_dispatch: # 手動実行を許可
  push:
    branches:
      - main  # デプロイ対象ブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Node.jsをセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      # 3. 依存関係インストール
      - name: Install dependencies
        run: npm ci

      # 4. ビルド
      - name: Build
        run: npm run build

      # 5. 日付情報を環境変数に保存
      - name: Set timestamp
        run: echo "DEPLOY_DIR=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      # 6. artifactを取っておく
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact_${{ env.DEPLOY_DIR }}
          path: dist/
          retention-days: 15

      # 7. AWS認証設定
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1  # 東京リージョン

      # 8. タイムスタンプディレクトリアップロード
      - name: Sync files to S3
        run: |
          aws s3 sync ./dist s3://weather-chart-deploy-item-strage/${{ env.DEPLOY_DIR }} --delete


      # 9. 最新版ディレクトリも更新
      - name: Update latest directory
        run: |
          aws s3 sync ./dist s3://weather-chart-deploy-item-strage/latest --delet

