
name: Deploy to S3

on:
  workflow_dispatch: # 手動実行を許可
  push:
    branches:
      - main  # デプロイ対象ブランチ

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [dev, stg, prd]
    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Node.jsをセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. 依存関係インストール
      - name: Install dependencies
        run: npm ci

      # 4. ビルド
      - name: Build (${{ matrix.mode }})
        run: |
          npm run build-${{ matrix.mode }}

      # 5. 日付情報を環境変数に保存
      - name: Set timestamp
        run: echo "DEPLOY_DIR=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      # 6. artifactを取っておく
      - name: Upload artifact (${{ matrix.mode }})
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.mode }}-${{ env.DEPLOY_DIR }}
          path: dist

      # 8. タイムスタンプディレクトリアップロード
      - name: Sync files to S3
        run: |
          aws s3 sync ./dist s3://weather-chart-deploy-item-strage/${{ env.DEPLOY_DIR }}_${{ matrix.mode }} --delete


      # 9. 最新版ディレクトリも更新
      - name: Update latest directory
        run: |
          aws s3 sync ./dist s3://weather-chart-deploy-item-strage/latest/${{ matrix.mode }} --delet
